dbt_mssql:
  target: prod
  outputs:
    prod:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('MSSQL_HOST') }}"
      port: "{{ env_var('MSSQL_PORT') }}"                   
      database: "{{ env_var('MSSQL_DB') }}"
      schema: "{{ env_var('MSSQL_SCHEMA') }}"                       
      user: "{{ env_var('MSSQL_USER') }}"
      password: "{{ env_var('MSSQL_PASSWORD') }}"
      encrypt: false                    
